//------------------------------------------------------------------------
//	7.12.2020 -- file generated by @laroi 
//------------------------------------------------------------------------

#include "stdafx.h"
#include ".\stalldata.h"


DWORD	CStallData::m_dwID=0;
string	CStallData::m_strName="";
string	CStallData::m_strMottoName="";
CStallData::eType	CStallData::m_eType=CStallData::selling;
DWORD	CStallData::m_dwLv=0;
DWORD	CStallData::m_dwMasterID=0;
string	CStallData::m_strMasterName="";
DWORD	CStallData::m_dwMemberCount=0;
DWORD	CStallData::m_dwMaxMembers=0;
CStallData::eState	CStallData::m_eState=CStallData::buying;
__int64	CStallData::m_i64Exp=0;
__int64	CStallData::m_i64Money=0;
__int64	CStallData::m_i64RemainTime=0;

CStallData::CStallData(void)
{
}

CStallData::~CStallData(void)
{
}

void CStallData::LoadData(sStallData data)
{
	m_dwID=data.stall_id;
	m_strName=data.stall_name;
	m_strMottoName=data.stall_motto_name;
	m_eType=data.stall_type;
	m_strMasterName=data.stall_master_name;
	m_i64Exp=data.stall_experience;
	m_i64Money=data.stall_money;
	m_dwMemberCount=data.stall_member_count;
	m_dwMaxMembers=data.stall_member_max;
	m_eState=data.stall_state;
	m_i64RemainTime=data.stall_remain_time;
	m_dwLv=1;
}

void CStallData::Reset()
{
	m_dwID=0;
	m_strName="";
	m_strMottoName="";
	m_eType=CStallData::selling;
	m_dwLv=0;
	m_dwMasterID=0;
	m_strMasterName="";
	m_dwMemberCount=0;
	m_dwMaxMembers=0;
	m_eState=CStallData::buying;
	m_i64Exp=0;
	m_i64Money=0;
	m_i64RemainTime=0;
}